stages:
  - build
  - test
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/kombinator/$CI_COMMIT_TAG

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH || $CI_COMMIT_TAG'

build:ubuntu:18.04:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
  image: ubuntu:18.04
  before_script:
    - apt-get update -y && apt install build-essential git wget p7zip-full curl libssl-dev -y
    - wget https://nim-lang.org/choosenim/init.sh
    - sh init.sh -y
    - rm init.sh
    - export PATH=/root/.nimble/bin:$PATH
  script:
    - nimble build -y
    - chmod +x bin/kombinator
  artifacts:
    paths:
      - bin/kombinator

windows:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
  tags:
    - shared-windows
  before_script:
    - choco install -y choosenim
    - $env:Path += ";C:\Users\gitlab_runner\.nimble\bin"
    - choosenim.exe 1.4.2 -y
  script:
    - nimble.exe build -y
  artifacts:
    paths:
      - bin/kombinator.exe

test:ubuntu:18.04:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG'
      when: never
    - when: on_success
  image: ubuntu:18.04
  before_script:
    - apt-get update -y && apt install build-essential git wget p7zip-full curl libssl-dev -y
    - wget https://nim-lang.org/choosenim/init.sh
    - sh init.sh -y
    - rm init.sh
    - export PATH=/root/.nimble/bin:$PATH
  script:
    - apt install ffmpeg -y
    - nimble test -y

upload:
  rules:
    - if: $CI_COMMIT_TAG
    - when: never
  image: curlimages/curl:latest
  stage: upload
  script:
    - mv bin/kombinator.exe bin/kombinator-$CI_COMMIT_TAG-windows-amd64.exe
    - |
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/kombinator-$CI_COMMIT_TAG-windows-amd64.exe $PACKAGE_REGISTRY_URL/kombinator-$CI_COMMIT_TAG-windows-amd64.exe
    - mv bin/kombinator bin/kombinator-$CI_COMMIT_TAG-linux-amd64
    - |
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/kombinator-$CI_COMMIT_TAG-linux-amd64 $PACKAGE_REGISTRY_URL/kombinator-$CI_COMMIT_TAG-linux-amd64

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
    - when: never
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"kombinator-$CI_COMMIT_TAG-linux-amd64\",\"url\":\"$PACKAGE_REGISTRY_URL/kombinator-$CI_COMMIT_TAG-linux-amd64\"}" \
        --assets-link "{\"name\":\"kombinator-$CI_COMMIT_TAG-windows-amd64.exe\",\"url\":\"$PACKAGE_REGISTRY_URL/kombinator-$CI_COMMIT_TAG-windows-amd64.exe\"}"

